#pragma once

#include <windows.h>
#include <vector>

vector <pair<PCWSTR, DWORD>> vDesiredAccessList{
	{L"DELETE", DELETE},
	{L"READ_CONTROL", READ_CONTROL},
	{L"WRITE_OWNER", WRITE_OWNER},
	{L"SYNCHRONIZE", SYNCHRONIZE},
	{L"STANDARD_RIGHTS_REQUIRED", STANDARD_RIGHTS_REQUIRED},
	{L"ACCESS_SYSTEM_SECURITY", ACCESS_SYSTEM_SECURITY},
	{L"WRITE_DAC", WRITE_DAC},
	{L"PROCESS_TERMINATE", PROCESS_TERMINATE},
	{L"PROCESS_CREATE_THREAD", PROCESS_CREATE_THREAD},
	{L"PROCESS_SET_SESSIONID", PROCESS_SET_SESSIONID},
	{L"PROCESS_VM_OPERATION", PROCESS_VM_OPERATION},
	{L"PROCESS_VM_READ", PROCESS_VM_READ},
	{L"PROCESS_VM_WRITE", PROCESS_VM_WRITE},
	{L"PROCESS_DUP_HANDLE", PROCESS_DUP_HANDLE},
	{L"PROCESS_CREATE_PROCESS", PROCESS_CREATE_PROCESS},
	{L"PROCESS_SET_QUOTA", PROCESS_SET_QUOTA},
	{L"PROCESS_SET_INFORMATION", PROCESS_SET_INFORMATION},
	{L"PROCESS_QUERY_INFORMATION", PROCESS_QUERY_INFORMATION},
	{L"PROCESS_SUSPEND_RESUME", PROCESS_SUSPEND_RESUME},
	{L"PROCESS_QUERY_LIMITED_INFORMATION", PROCESS_QUERY_LIMITED_INFORMATION},
	{L"PROCESS_SET_LIMITED_INFORMATION", PROCESS_SET_LIMITED_INFORMATION}
};